require('core-js/proposals/reflect-metadata');
require('zone.js');
require('ts-node/register');
require('jsdom-global/register');
require('@angular/core/testing').TestBed.resetTestEnvironment();
require('@angular/core/testing').TestBed.initTestEnvironment(
	require('@angular/platform-browser-dynamic/testing').BrowserDynamicTestingModule,
	require('@angular/platform-browser-dynamic/testing').platformBrowserDynamicTesting()
);
